import os
import sys
import secrets
import string
import sqlite3
import asyncio
from datetime import datetime, timedelta
import aiohttp
from aiohttp import web
import discord
from discord import app_commands
from discord.ext import commands

# -------------------------------------------------------------
# Configuration
# -------------------------------------------------------------
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN", "YOUR_DISCORD_BOT_TOKEN_HERE")
PORT = int(os.getenv("PORT", "10000"))
DB_FILE = os.getenv("DB_FILE", "licenses.db")

APP_NAME = "PREMIUM EXE"
APP_VERSION = "1.0.0"
APP_DEVELOPER = "MICKEYXMINNIE"
EMBED_COLOR = 0xFF1E27  # Neon Red

# -------------------------------------------------------------
# Database Setup
# -------------------------------------------------------------
def get_db():
    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    with get_db() as conn:
        conn.execute("""
            CREATE TABLE IF NOT EXISTS licenses (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                key_code TEXT UNIQUE NOT NULL,
                duration_days INTEGER NOT NULL,
                hwid TEXT DEFAULT NULL,
                created_at TEXT NOT NULL,
                activated_at TEXT DEFAULT NULL,
                expires_at TEXT DEFAULT NULL,
                is_active INTEGER DEFAULT 1,
                created_by TEXT DEFAULT 'Admin',
                note TEXT DEFAULT ''
            );
        """)
        conn.commit()

init_db()

def generate_key_string(prefix="PREMIUM"):
    chars = string.ascii_uppercase + string.digits
    parts = [''.join(secrets.choice(chars) for _ in range(4)) for _ in range(3)]
    return f"{prefix}-{parts[0]}-{parts[1]}-{parts[2]}"

# -------------------------------------------------------------
# Discord Bot Setup
# -------------------------------------------------------------
intents = discord.Intents.default()
bot = commands.Bot(command_prefix="!", intents=intents)

@bot.event
async def on_ready():
    print(f"[BOT] Logged in as {bot.user.name} ({bot.user.id})")
    try:
        synced = await bot.tree.sync()
        print(f"[BOT] Synced {len(synced)} slash commands")
    except Exception as e:
        print(f"[BOT] Error syncing commands: {e}")
    await bot.change_presence(activity=discord.Game(name=f"{APP_NAME} v{APP_VERSION}"))

# -------------------------------------------------------------
# Slash Commands
# -------------------------------------------------------------
@bot.tree.command(name="genkey", description="Generate a new license key for PREMIUM EXE")
@app_commands.describe(
    days="Duration in days (e.g. 1, 7, 30, 365, or 0 for Lifetime)",
    note="Optional user or buyer note"
)
async def genkey(interaction: discord.Interaction, days: int, note: str = ""):
    if days < 0:
        await interaction.response.send_message("❌ Days cannot be negative!", ephemeral=True)
        return

    key_code = generate_key_string()
    created_at = datetime.utcnow().isoformat()
    created_by = f"{interaction.user.name} ({interaction.user.id})"

    with get_db() as conn:
        conn.execute("""
            INSERT INTO licenses (key_code, duration_days, created_at, created_by, note)
            VALUES (?, ?, ?, ?, ?)
        """, (key_code, days, created_at, created_by, note))
        conn.commit()

    duration_text = "♾️ Lifetime" if days == 0 else f"⏳ {days} Days"

    embed = discord.Embed(
        title=f"🔑 License Key Created — {APP_NAME}",
        description="Here is the newly generated license key for the customer.",
        color=EMBED_COLOR
    )
    embed.add_field(name="📋 License Key", value=f"```{key_code}```", inline=False)
    embed.add_field(name="⏱️ Duration", value=duration_text, inline=True)
    embed.add_field(name="💻 Status", value="Unactivated (Ready to bind)", inline=True)
    if note:
        embed.add_field(name="📝 Note", value=note, inline=True)
    
    # Matching the user's photo specification
    embed.add_field(name="📌 Version", value=f"**{APP_VERSION}**", inline=True)
    embed.add_field(name="👑 Developed by", value=f"**{APP_DEVELOPER}**", inline=True)
    embed.set_footer(text=f"{APP_NAME} License Engine • Generated by {interaction.user.name}")
    embed.timestamp = datetime.utcnow()

    await interaction.response.send_message(embed=embed)

@bot.tree.command(name="checkkey", description="Check details of a license key")
@app_commands.describe(key="The license key to inspect")
async def checkkey(interaction: discord.Interaction, key: str):
    key = key.strip().upper()
    with get_db() as conn:
        cur = conn.execute("SELECT * FROM licenses WHERE key_code = ?", (key,))
        row = cur.fetchone()

    if not row:
        await interaction.response.send_message(f"❌ Key `{key}` not found in database.", ephemeral=True)
        return

    status = "Active ✅" if row["is_active"] else "Revoked ⛔"
    duration = "Lifetime ♾️" if row["duration_days"] == 0 else f"{row['duration_days']} Days"
    hwid = f"`{row['hwid'][:16]}...`" if row["hwid"] else "None (Unused)"
    activated = row["activated_at"] or "Not yet activated"
    expires = row["expires_at"] or ("Lifetime" if row["duration_days"] == 0 else "Pending activation")

    embed = discord.Embed(title=f"🔍 Key Details — {key}", color=EMBED_COLOR)
    embed.add_field(name="Status", value=status, inline=True)
    embed.add_field(name="Duration", value=duration, inline=True)
    embed.add_field(name="HWID Lock", value=hwid, inline=True)
    embed.add_field(name="Activated At", value=activated, inline=True)
    embed.add_field(name="Expires At", value=expires, inline=True)
    embed.add_field(name="Version", value=f"**{APP_VERSION}**", inline=True)
    embed.add_field(name="Developed by", value=f"**{APP_DEVELOPER}**", inline=True)
    if row["note"]:
        embed.add_field(name="Note", value=row["note"], inline=False)
    embed.set_footer(text=f"{APP_NAME} Management")

    await interaction.response.send_message(embed=embed)

@bot.tree.command(name="resethwid", description="Reset HWID lock for a license key")
@app_commands.describe(key="License key to reset HWID for")
async def resethwid(interaction: discord.Interaction, key: str):
    key = key.strip().upper()
    with get_db() as conn:
        cur = conn.execute("SELECT * FROM licenses WHERE key_code = ?", (key,))
        row = cur.fetchone()
        if not row:
            await interaction.response.send_message(f"❌ Key `{key}` was not found.", ephemeral=True)
            return

        conn.execute("UPDATE licenses SET hwid = NULL WHERE key_code = ?", (key,))
        conn.commit()

    embed = discord.Embed(
        title="🔄 HWID Reset Successfully",
        description=f"Hardware ID lock for key `{key}` has been cleared.\nThe user can now bind it to a new PC.",
        color=0x00FF88
    )
    embed.set_footer(text=f"Reset by {interaction.user.name}")
    await interaction.response.send_message(embed=embed)

@bot.tree.command(name="delkey", description="Revoke/delete a license key")
@app_commands.describe(key="License key to revoke")
async def delkey(interaction: discord.Interaction, key: str):
    key = key.strip().upper()
    with get_db() as conn:
        cur = conn.execute("SELECT * FROM licenses WHERE key_code = ?", (key,))
        row = cur.fetchone()
        if not row:
            await interaction.response.send_message(f"❌ Key `{key}` was not found.", ephemeral=True)
            return

        conn.execute("UPDATE licenses SET is_active = 0 WHERE key_code = ?", (key,))
        conn.commit()

    await interaction.response.send_message(f"⛔ Key `{key}` has been revoked and can no longer be used.")

@bot.tree.command(name="listkeys", description="List recent license keys")
async def listkeys(interaction: discord.Interaction):
    with get_db() as conn:
        cur = conn.execute("SELECT * FROM licenses ORDER BY id DESC LIMIT 10")
        rows = cur.fetchall()

    if not rows:
        await interaction.response.send_message("No keys found in database.", ephemeral=True)
        return

    lines = []
    for r in rows:
        stat = "✅" if r["is_active"] else "❌"
        hw = "🔒" if r["hwid"] else "🔓"
        dur = "Life" if r["duration_days"] == 0 else f"{r['duration_days']}d"
        lines.append(f"`{r['key_code']}` | {dur} | {stat} {hw}")

    embed = discord.Embed(
        title=f"📋 Recent Keys — {APP_NAME}",
        description="\n".join(lines),
        color=EMBED_COLOR
    )
    embed.set_footer(text=f"Showing latest {len(rows)} keys")
    await interaction.response.send_message(embed=embed)

@bot.tree.command(name="info", description="Show bot information & developer showoff")
async def info(interaction: discord.Interaction):
    with get_db() as conn:
        total = conn.execute("SELECT COUNT(*) FROM licenses").fetchone()[0]
        active = conn.execute("SELECT COUNT(*) FROM licenses WHERE is_active = 1").fetchone()[0]
        used = conn.execute("SELECT COUNT(*) FROM licenses WHERE hwid IS NOT NULL").fetchone()[0]

    embed = discord.Embed(
        title=f"🛡️ {APP_NAME} — Authentication Engine",
        description="High performance license authentication and protection server.",
        color=EMBED_COLOR
    )
    embed.add_field(name="Version:", value=f"**{APP_VERSION}**", inline=True)
    embed.add_field(name="Developed by:", value=f"**{APP_DEVELOPER}**", inline=True)
    embed.add_field(name="System Status", value="🟢 Online", inline=True)
    embed.add_field(name="Total Keys", value=str(total), inline=True)
    embed.add_field(name="Active Keys", value=str(active), inline=True)
    embed.add_field(name="Redeemed (PCs)", value=str(used), inline=True)
    embed.set_footer(text=f"{APP_NAME} • Official Bot")
    embed.timestamp = datetime.utcnow()
    await interaction.response.send_message(embed=embed)

# -------------------------------------------------------------
# Web HTTP REST API (aiohttp)
# -------------------------------------------------------------
routes = web.RouteTableDef()

@routes.get('/')
async def root_handler(request):
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{APP_NAME} License Server</title>
        <style>
            body {{
                background: #0d0e10;
                color: #e0e0e0;
                font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
            }}
            .card {{
                background: #16181c;
                border: 1px solid #2b2e35;
                box-shadow: 0 0 20px rgba(255, 30, 39, 0.2);
                border-radius: 12px;
                padding: 40px;
                text-align: center;
                max-width: 420px;
            }}
            h1 {{ color: #ff1e27; margin-bottom: 8px; }}
            .dev {{ color: #ff3333; font-weight: bold; }}
            .badge {{
                display: inline-block;
                background: rgba(0, 255, 128, 0.1);
                color: #00ff80;
                border: 1px solid #00ff80;
                padding: 4px 12px;
                border-radius: 20px;
                font-size: 13px;
                margin-top: 15px;
            }}
        </style>
    </head>
    <body>
        <div class="card">
            <h1>{APP_NAME}</h1>
            <p>Version: <strong>{APP_VERSION}</strong></p>
            <p>Developed by: <span class="dev">{APP_DEVELOPER}</span></p>
            <div class="badge">● Authentication API Online</div>
        </div>
    </body>
    </html>
    """
    return web.Response(text=html, content_type='text/html')

@routes.get('/api/status')
async def api_status(request):
    return web.json_response({
        "status": "online",
        "app": APP_NAME,
        "version": APP_VERSION,
        "developed_by": APP_DEVELOPER,
        "timestamp": datetime.utcnow().isoformat()
    })

@routes.post('/api/verify')
async def api_verify(request):
    try:
        data = await request.json()
    except Exception:
        return web.json_response({"success": False, "message": "Invalid JSON body"}, status=400)

    key_input = (data.get("key") or "").strip().upper()
    hwid_input = (data.get("hwid") or "").strip()

    if not key_input:
        return web.json_response({"success": False, "message": "License key is required."}, status=400)
    if not hwid_input:
        return web.json_response({"success": False, "message": "Hardware ID is required."}, status=400)

    with get_db() as conn:
        cur = conn.execute("SELECT * FROM licenses WHERE key_code = ?", (key_input,))
        row = cur.fetchone()

        if not row:
            return web.json_response({"success": False, "message": "Invalid license key!"})

        if not row["is_active"]:
            return web.json_response({"success": False, "message": "This license key has been revoked by admin."})

        # Check HWID Binding
        db_hwid = row["hwid"]
        now = datetime.utcnow()

        if not db_hwid:
            # First activation: bind HWID and compute expiry
            activated_at_str = now.isoformat()
            duration = row["duration_days"]
            if duration > 0:
                expires_dt = now + timedelta(days=duration)
                expires_str = expires_dt.isoformat()
            else:
                expires_str = None  # Lifetime

            conn.execute("""
                UPDATE licenses 
                SET hwid = ?, activated_at = ?, expires_at = ?
                WHERE key_code = ?
            """, (hwid_input, activated_at_str, expires_str, key_input))
            conn.commit()
            
            days_left = duration if duration > 0 else 99999
            return web.json_response({
                "success": true,
                "message": "License activated successfully!",
                "key": key_input,
                "expires": expires_str or "Lifetime",
                "days_left": days_left,
                "version": APP_VERSION,
                "developed_by": APP_DEVELOPER
            })

        # Existing activation: verify HWID
        if db_hwid != hwid_input:
            return web.json_response({
                "success": False,
                "message": "HWID mismatch! This key is locked to another computer. Ask your admin to reset HWID."
            })

        # Check expiration
        expires_str = row["expires_at"]
        if expires_str:
            try:
                exp_dt = datetime.fromisoformat(expires_str)
                if now > exp_dt:
                    return web.json_response({
                        "success": False,
                        "message": f"License expired on {exp_dt.strftime('%Y-%m-%d %H:%M:%S')} UTC!"
                    })
                days_left = max(0, (exp_dt - now).days)
            except Exception:
                days_left = 30
        else:
            days_left = 99999

        return web.json_response({
            "success": True,
            "message": "License active and valid.",
            "key": key_input,
            "expires": expires_str or "Lifetime",
            "days_left": days_left,
            "version": APP_VERSION,
            "developed_by": APP_DEVELOPER
        })

# -------------------------------------------------------------
# Main Application Runner
# -------------------------------------------------------------
async def start_web_server():
    app = web.Application()
    app.add_routes(routes)
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, '0.0.0.0', PORT)
    await site.start()
    print(f"[API] HTTP License Server running on http://0.0.0.0:{PORT}")

async def main():
    # Start web server in asyncio event loop
    await start_web_server()
    
    if DISCORD_TOKEN == "YOUR_DISCORD_BOT_TOKEN_HERE" or not DISCORD_TOKEN:
        print("\n" + "=" * 60)
        print("⚠️  WARNING: DISCORD_TOKEN is not configured in environment!")
        print("   The HTTP verification API is active and functioning.")
        print("   To enable the Discord bot commands, set the DISCORD_TOKEN.")
        print("=" * 60 + "\n")
        # Keep web server alive
        while True:
            await asyncio.sleep(3600)
    else:
        print("[BOT] Starting Discord bot...")
        await bot.start(DISCORD_TOKEN)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        print("Shutting down...")
